with open('index.html','r') as f:
    content = f.read()

features = {
    'cycleTheme': 'cycleTheme' in content,
    'themeToggleBtn': 'themeToggleBtn' in content,
    'dmConductModal': 'dmConductModal' in content,
    'openDmConduct': 'openDmConduct' in content,
    'handleDmSubmit': 'handleDmSubmit' in content,
    'dmDate': 'dmDate' in content,
    'dmShift': 'dmShift' in content,
    'dmLocation': 'dmLocation' in content,
    'dmAttendees': 'dmAttendees' in content,
    'dmTopics': 'dmTopics' in content,
    'dmIssues': 'dmIssues' in content,
    'dmActions': 'dmActions' in content,
    'dmConductedBy': 'dmConductedBy' in content,
    'dm_records': 'dm_records' in content,
    'fetchLoggedReports': 'fetchLoggedReports' in content,
    'fetchDashboardMetrics': 'fetchDashboardMetrics' in content,
    'fetchSafetyAlerts': 'fetchSafetyAlerts' in content,
    'fetchLibraryDocuments': 'fetchLibraryDocuments' in content,
    'fetchUpcomingEvents': 'fetchUpcomingEvents' in content,
    'fetchCirculars': 'fetchCirculars' in content,
    'fetchWallOfFame': 'fetchWallOfFame' in content,
    'fetchGallery': 'fetchGallery' in content,
    'fetchTrainingRecords': 'fetchTrainingRecords' in content,
    'reportsLogContent': 'reportsLogContent' in content,
    'validateOfficerLogin': 'validateOfficerLogin' in content,
    'fallbackOfficerLogin': 'fallbackOfficerLogin' in content,
    'handleFormSubmit': 'handleFormSubmit' in content,
    'triggerLiveNameLookup': 'triggerLiveNameLookup' in content,
    'openReportingForm': 'openReportingForm' in content,
    'toggleLanguage': 'toggleLanguage' in content,
    'openSafetyDashboard': 'openSafetyDashboard' in content,
    'openTrainingManagement': 'openTrainingManagement' in content,
    'openSafetyAlertsModal': 'openSafetyAlertsModal' in content,
    'openEmergencyPrepModal': 'openEmergencyPrepModal' in content,
    'openAllPolicyModal': 'openAllPolicyModal' in content,
    'openEmergencyModal': 'openEmergencyModal' in content,
    'openOfficerModal': 'openOfficerModal' in content,
    'openPublicSearchModal': 'openPublicSearchModal' in content,
    'openObservationSelectModal': 'openObservationSelectModal' in content,
    'openFeedbackSelectModal': 'openFeedbackSelectModal' in content,
    'openGrievanceSelectModal': 'openGrievanceSelectModal' in content,
    'openSuggestionSelectModal': 'openSuggestionSelectModal' in content,
    'openAccidentSelectModal': 'openAccidentSelectModal' in content,
    'openTslRules': 'openTslRules' in content,
    'openFeedbackForm': 'openFeedbackForm' in content,
    'handleTrainingFeedback': 'handleTrainingFeedback' in content,
    'downloadCertificate': 'downloadCertificate' in content,
    'setRating': 'setRating' in content,
    'resetRatingButtons': 'resetRatingButtons' in content,
    'sanitizeInput': 'sanitizeInput' in content,
    'checkRateLimit': 'checkRateLimit' in content,
    'escapeHtml': 'escapeHtml' in content,
    'updateDateDisplay': 'updateDateDisplay' in content,
    'showAlertCategory': 'showAlertCategory' in content,
    'backToAlertCategories': 'backToAlertCategories' in content,
    'prevMonth': 'prevMonth' in content,
    'nextMonth': 'nextMonth' in content,
    'backToPlantSelect': 'backToPlantSelect' in content,
    'openDashboardFromSelect': 'openDashboardFromSelect' in content,
    'renderDashboardForMonth': 'renderDashboardForMonth' in content,
    'updateChartBars': 'updateChartBars' in content,
    'selectPlantAndOpenDashboard': 'selectPlantAndOpenDashboard' in content,
    'forgotUsername': 'forgotUsername' in content,
    'forgotPassword': 'forgotPassword' in content,
    'logoutOfficer': 'logoutOfficer' in content,
    'executeLiveSearch': 'executeLiveSearch' in content,
    'executePublicLiveSearch': 'executePublicLiveSearch' in content,
    'selectAccidentType': 'selectAccidentType' in content,
    'selectObservationType': 'selectObservationType' in content,
    'selectFeedbackType': 'selectFeedbackType' in content,
    'selectGrievanceType': 'selectGrievanceType' in content,
    'selectSuggestionType': 'selectSuggestionType' in content,
    'closeReportingForm': 'closeReportingForm' in content,
    'closeOfficerModal': 'closeOfficerModal' in content,
    'closePublicSearchModal': 'closePublicSearchModal' in content,
    'closeAccidentSelectModal': 'closeAccidentSelectModal' in content,
    'closeObservationSelectModal': 'closeObservationSelectModal' in content,
    'closeFeedbackSelectModal': 'closeFeedbackSelectModal' in content,
    'closeGrievanceSelectModal': 'closeGrievanceSelectModal' in content,
    'closeSuggestionSelectModal': 'closeSuggestionSelectModal' in content,
    'closeAllPolicyModal': 'closeAllPolicyModal' in content,
    'closeEmergencyPrepModal': 'closeEmergencyPrepModal' in content,
    'closeSafetyDashboard': 'closeSafetyDashboard' in content,
    'closeSafetyAlertsModal': 'closeSafetyAlertsModal' in content,
    'closeTrainingManagement': 'closeTrainingManagement' in content,
    'closeTrainingFeedback': 'closeTrainingFeedback' in content,
    'toggleReportsLog': 'toggleReportsLog' in content,
    'allPlantMonthlyData': 'allPlantMonthlyData' in content,
    'safetyAlertsData': 'safetyAlertsData' in content,
    'currentLang': 'currentLang' in content,
    'activeReportType': 'activeReportType' in content,
    'currentAuthenticatedPlant': 'currentAuthenticatedPlant' in content,
    'themeIndex': 'themeIndex' in content,
    'themeNames': 'themeNames' in content,
    'SAFEX_CONFIG': 'SAFEX_CONFIG' in content,
    '_supabase': '_supabase' in content,
    '_rateLimitStore': '_rateLimitStore' in content,
    'dashboardCurrentMonth': 'dashboardCurrentMonth' in content,
    'selectedDashboardPlant': 'selectedDashboardPlant' in content,
    'monthNames': 'monthNames' in content,
}

print("=== FEATURE CHECK ===")
for name, present in features.items():
    status = "✅" if present else "❌"
    print(f"{status} {name}")

print(f"\nFile size: {len(content)} bytes")
print(f"Has </html>: {'</html>' in content}")
print(f"</script> count: {content.count('</script>')}")
