const fs = require('fs');
const content = fs.readFileSync('index.html', 'utf8');

const features = {
  cycleTheme: content.includes('cycleTheme'),
  themeToggleBtn: content.includes('themeToggleBtn'),
  dmConductModal: content.includes('dmConductModal'),
  openDmConduct: content.includes('openDmConduct'),
  handleDmSubmit: content.includes('handleDmSubmit'),
  dmDate: content.includes('dmDate'),
  dmShift: content.includes('dmShift'),
  dmLocation: content.includes('dmLocation'),
  dmAttendees: content.includes('dmAttendees'),
  dmTopics: content.includes('dmTopics'),
  dmIssues: content.includes('dmIssues'),
  dmActions: content.includes('dmActions'),
  dmConductedBy: content.includes('dmConductedBy'),
  dm_records: content.includes('dm_records'),
  fetchLoggedReports: content.includes('fetchLoggedReports'),
  fetchDashboardMetrics: content.includes('fetchDashboardMetrics'),
  fetchSafetyAlerts: content.includes('fetchSafetyAlerts'),
  fetchLibraryDocuments: content.includes('fetchLibraryDocuments'),
  fetchUpcomingEvents: content.includes('fetchUpcomingEvents'),
  fetchCirculars: content.includes('fetchCirculars'),
  fetchWallOfFame: content.includes('fetchWallOfFame'),
  fetchGallery: content.includes('fetchGallery'),
  fetchTrainingRecords: content.includes('fetchTrainingRecords'),
  reportsLogContent: content.includes('reportsLogContent'),
  validateOfficerLogin: content.includes('validateOfficerLogin'),
  fallbackOfficerLogin: content.includes('fallbackOfficerLogin'),
  handleFormSubmit: content.includes('handleFormSubmit'),
  triggerLiveNameLookup: content.includes('triggerLiveNameLookup'),
  openReportingForm: content.includes('openReportingForm'),
  toggleLanguage: content.includes('toggleLanguage'),
  openSafetyDashboard: content.includes('openSafetyDashboard'),
  openTrainingManagement: content.includes('openTrainingManagement'),
  openSafetyAlertsModal: content.includes('openSafetyAlertsModal'),
  openEmergencyPrepModal: content.includes('openEmergencyPrepModal'),
  openAllPolicyModal: content.includes('openAllPolicyModal'),
  openEmergencyModal: content.includes('openEmergencyModal'),
  openOfficerModal: content.includes('openOfficerModal'),
  openPublicSearchModal: content.includes('openPublicSearchModal'),
  openObservationSelectModal: content.includes('openObservationSelectModal'),
  openFeedbackSelectModal: content.includes('openFeedbackSelectModal'),
  openGrievanceSelectModal: content.includes('openGrievanceSelectModal'),
  openSuggestionSelectModal: content.includes('openSuggestionSelectModal'),
  openAccidentSelectModal: content.includes('openAccidentSelectModal'),
  openTslRules: content.includes('openTslRules'),
  openFeedbackForm: content.includes('openFeedbackForm'),
  handleTrainingFeedback: content.includes('handleTrainingFeedback'),
  downloadCertificate: content.includes('downloadCertificate'),
  setRating: content.includes('setRating'),
  resetRatingButtons: content.includes('resetRatingButtons'),
  sanitizeInput: content.includes('sanitizeInput'),
  checkRateLimit: content.includes('checkRateLimit'),
  escapeHtml: content.includes('escapeHtml'),
  updateDateDisplay: content.includes('updateDateDisplay'),
  showAlertCategory: content.includes('showAlertCategory'),
  backToAlertCategories: content.includes('backToAlertCategories'),
  prevMonth: content.includes('prevMonth'),
  nextMonth: content.includes('nextMonth'),
  backToPlantSelect: content.includes('backToPlantSelect'),
  openDashboardFromSelect: content.includes('openDashboardFromSelect'),
  renderDashboardForMonth: content.includes('renderDashboardForMonth'),
  updateChartBars: content.includes('updateChartBars'),
  selectPlantAndOpenDashboard: content.includes('selectPlantAndOpenDashboard'),
  forgotUsername: content.includes('forgotUsername'),
  forgotPassword: content.includes('forgotPassword'),
  logoutOfficer: content.includes('logoutOfficer'),
  executeLiveSearch: content.includes('executeLiveSearch'),
  executePublicLiveSearch: content.includes('executePublicLiveSearch'),
  selectAccidentType: content.includes('selectAccidentType'),
  selectObservationType: content.includes('selectObservationType'),
  selectFeedbackType: content.includes('selectFeedbackType'),
  selectGrievanceType: content.includes('selectGrievanceType'),
  selectSuggestionType: content.includes('selectSuggestionType'),
  closeReportingForm: content.includes('closeReportingForm'),
  closeOfficerModal: content.includes('closeOfficerModal'),
  closePublicSearchModal: content.includes('closePublicSearchModal'),
  closeAccidentSelectModal: content.includes('closeAccidentSelectModal'),
  closeObservationSelectModal: content.includes('closeObservationSelectModal'),
  closeFeedbackSelectModal: content.includes('closeFeedbackSelectModal'),
  closeGrievanceSelectModal: content.includes('closeGrievanceSelectModal'),
  closeSuggestionSelectModal: content.includes('closeSuggestionSelectModal'),
  closeAllPolicyModal: content.includes('closeAllPolicyModal'),
  closeEmergencyPrepModal: content.includes('closeEmergencyPrepModal'),
  closeSafetyDashboard: content.includes('closeSafetyDashboard'),
  closeSafetyAlertsModal: content.includes('closeSafetyAlertsModal'),
  closeTrainingManagement: content.includes('closeTrainingManagement'),
  closeTrainingFeedback: content.includes('closeTrainingFeedback'),
  toggleReportsLog: content.includes('toggleReportsLog'),
  allPlantMonthlyData: content.includes('allPlantMonthlyData'),
  safetyAlertsData: content.includes('safetyAlertsData'),
  currentLang: content.includes('currentLang'),
  activeReportType: content.includes('activeReportType'),
  currentAuthenticatedPlant: content.includes('currentAuthenticatedPlant'),
  themeIndex: content.includes('themeIndex'),
  themeNames: content.includes('themeNames'),
  SAFEX_CONFIG: content.includes('SAFEX_CONFIG'),
  _supabase: content.includes('_supabase'),
  _rateLimitStore: content.includes('_rateLimitStore'),
  dashboardCurrentMonth: content.includes('dashboardCurrentMonth'),
  selectedDashboardPlant: content.includes('selectedDashboardPlant'),
  monthNames: content.includes('monthNames'),
};

console.log('=== FEATURE CHECK ===');
for (const [name, present] of Object.entries(features)) {
  console.log(`${present ? '✅' : '❌'} ${name}`);
}

console.log(`\nFile size: ${content.length} bytes`);
console.log(`Has </html>: ${content.includes('</html>')}`);
console.log(`</script> count: ${(content.match(/<\/script>/g) || []).length}`);
